spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: your-secret-key
  expiration: 86400000